[package]
name = "phi3-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "phi3"
path = "bin.rs"

[dependencies]
candle-core.workspace = true
clap = { version = "4.5", features = ["derive"] }
phi3-lib = { as = "phi3", path = "../phi3-lib" }
tracing = "0.1"
tracing-subscriber = "0.3"
